const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const tempHome = fs.mkdtempSync(path.join(os.tmpdir(), 'wcp-operator-email-home-'));
process.env.HOME = tempHome;
process.env.WORKSPACE_PI_GATEWAY_TOKEN = 'test-token';
const { createGatewayServer } = require('../src/server');
const { createMockProvider } = require('../src/email-composition-provider');
function makeConfig(root) { return { port: 0, workspaceRoot: root, snapshotRoot: path.join(root, '.snapshots'), archiveRoot: path.join(root, '.archive'), auditLogPath: path.join(root, '.audit.log'), approvedRoots: ['.'], browseRoots: ['.'], tierRules: [{ pattern: '**', tier: 1 }], auth: { envVar: 'WORKSPACE_PI_GATEWAY_TOKEN' } }; }
async function request(baseUrl, method, pathname, body) { const res = await fetch(`${baseUrl}${pathname}`, { method, headers: { Authorization: 'Bearer test-token', ...(body ? { 'Content-Type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined }); return { status: res.status, payload: await res.json() }; }
async function createEmailIntake(baseUrl, suffix) { const entityId = `entityOperatorEmail${suffix}`; const sourceId = `src_operator_email_${suffix}`; await request(baseUrl, 'POST', '/task-system/context-broker/fixture/register', { entity_id: entityId, sources: [{ source_id: sourceId, source_kind: 'email', source_ref: `operator-email-${suffix}`, role: 'dated_artifact', required_evidence: true, content: 'From: client@example.com\nDate: 2026-08-06T09:00:00Z\nSubject: Check-in\n\nCan you confirm this still works?', freshness_status: 'fresh', content_availability: 'full' }] }); return request(baseUrl, 'POST', '/task-intake/brief', { brief_text: 'Draft a reply to the exact client email.', work_type: 'email_reply_draft', entity: `Operator Email ${suffix}`, entity_id: entityId, source_refs: [sourceId], idempotency_key: `operator-email-${suffix}-v1` }); }
async function enableAuto(baseUrl) { return request(baseUrl, 'PATCH', '/task-system/operator-state', { mode: 'auto_one', max_risk: 'MEDIUM', allow_medium_prepare: true, work_waiting: true, active_lease_id: null, active_subtask_id: null }); }

test('operator-check completes an email reply through injected bounded provider/writer as an unsent verified Outlook draft', { concurrency: false }, async (t) => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'wcp-operator-email-success-')); const writerCalls = []; const providerCalls = []; const gateway = createGatewayServer({ config: makeConfig(root), authToken: 'test-token', compositionProvider: createMockProvider((request) => { providerCalls.push(request); return { schema: 'email-composition-response-v1', status: 'composed', mode: request.mode, recipient: request.identity.recipient, send: false, draft: { subject: 'Re: Dates', body: 'Hi,\n\nYes, that date still works.\n\nBest,' } }; }), emailDraftExecutor: async (_db, payload) => { writerCalls.push(payload); return { ok: true, verified: true, id: 'out_operator_mock', draft_id: 'draft_operator_mock', web_link: 'https://draft.example/operator', verification: { recipient_verified: true, subject: 'Re: Dates', body_hash: 'sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', body_length: 32, readback_body_length: 32, saved_at: '2026-08-30T14:00:00.000Z' } }; } }); const address = await gateway.start(0); const baseUrl = `http://127.0.0.1:${address.port}`; t.after(async () => gateway.close()); const intake = await createEmailIntake(baseUrl, 'Success'); await enableAuto(baseUrl); const result = await request(baseUrl, 'POST', '/task-system/operator-check'); assert.equal(result.payload.outcome, 'completed', JSON.stringify(result.payload)); assert.equal(result.payload.execution_result.status, 'draft_created_verified'); assert.equal(providerCalls.length, 1); assert.equal(providerCalls[0].no_send, true); assert.equal(writerCalls.length, 1); assert.equal(writerCalls[0].composition_package.no_send_proof.send_endpoint_called, false); assert.equal(writerCalls[0].composition_package.recipient_proof.strategy, 'createReplyAll_exact_inbound'); const state = await request(baseUrl, 'GET', '/task-system/operator-state'); assert.equal(state.payload.state.active_subtask_id, null); const subtask = await request(baseUrl, 'GET', `/subtasks/${intake.payload.subtasks[0].id}`); assert.equal(subtask.payload.entity.state, 'done'); });

test('operator-check retryably blocks and releases its lease when its email writer fails', { concurrency: false }, async (t) => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'wcp-operator-email-failure-')); const gateway = createGatewayServer({ config: makeConfig(root), authToken: 'test-token', compositionProvider: createMockProvider((request) => ({ schema: 'email-composition-response-v1', status: 'composed', mode: request.mode, recipient: request.identity.recipient, send: false, draft: { subject: null, body: 'Hi,\n\nYes.\n\nBest,' } })), emailDraftExecutor: async () => { const err = new Error('Mock Outlook writer unavailable'); err.code = 'MOCK_WRITER_DOWN'; throw err; } }); const address = await gateway.start(0); const baseUrl = `http://127.0.0.1:${address.port}`; t.after(async () => gateway.close()); const intake = await createEmailIntake(baseUrl, 'Failure'); await enableAuto(baseUrl); const result = await request(baseUrl, 'POST', '/task-system/operator-check'); assert.equal(result.payload.outcome, 'blocked'); assert.equal(result.payload.execution_result.status, 'draft_unverified'); assert.equal(result.payload.execution_result.retryable, true); const subtask = await request(baseUrl, 'GET', `/subtasks/${intake.payload.subtasks[0].id}`); assert.equal(subtask.payload.entity.state, 'blocked'); assert.ok(subtask.payload.entity.blockers_json.some((blocker) => blocker.code === 'MOCK_WRITER_DOWN' && blocker.retryable)); assert.equal((subtask.payload.entity.links_json || []).some((link) => link.status === 'draft_created_not_sent'), false); const state = await request(baseUrl, 'GET', '/task-system/operator-state'); assert.equal(state.payload.state.active_subtask_id, null); });

test('operator-check keeps non-email work claim-only', { concurrency: false }, async (t) => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'wcp-operator-non-email-')); const gateway = createGatewayServer({ config: makeConfig(root), authToken: 'test-token' }); const address = await gateway.start(0); const baseUrl = `http://127.0.0.1:${address.port}`; t.after(async () => gateway.close()); await request(baseUrl, 'POST', '/task-system/context-broker/fixture/register', { entity_id: 'entityOperatorDocument', sources: [{ source_id: 'src_operator_document', source_kind: 'sharepoint', source_ref: 'operator-document-current', role: 'current', content: 'Confirmed requirements.', freshness_status: 'fresh', content_availability: 'full' }, { source_id: 'src_operator_document_evidence', source_kind: 'sharepoint', source_ref: 'operator-document-evidence', role: 'dated_artifact', required_evidence: true, content: 'Supporting evidence.', freshness_status: 'fresh', content_availability: 'full' }] }); const intake = await request(baseUrl, 'POST', '/task-intake/brief', { brief_text: 'Write the client document for confirmed requirements.', work_type: 'client_document', entity: 'Operator Document', entity_id: 'entityOperatorDocument', source_refs: ['src_operator_document', 'src_operator_document_evidence'], idempotency_key: 'operator-document-v1' }); await enableAuto(baseUrl); const result = await request(baseUrl, 'POST', '/task-system/operator-check'); assert.equal(result.payload.outcome, 'claimed'); assert.equal(result.payload.execution_result, undefined); assert.equal(result.payload.selected.id, intake.payload.subtasks[0].id); assert.equal(result.payload.selected.state, 'in_progress'); });
