// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/arch-diagram/ArchDiagram.tsx": () => import("../components/mockups/arch-diagram/ArchDiagram.tsx")
};
